### ISSUE TITLE
did Cesium support the water mask now?

### ISSUE THREAD

**Issue by MichealWen** [abwood/cesium#8]
appreciate for your work,could you tell me the " quantized-mesh-1.0" support water mask now?

**Comment by abwood** [comment]
Hi Micheal,
The quantized-mesh-1.0 spec will officially support watermask very soon.  The updated world terrain tileset is being processed right now with the watermask feature and should be deployed next week.  Once deployed this pull request will be merged into Cesium shortly thereafter:
https://github.com/AnalyticalGraphicsInc/cesium/pull/2229

**Comment by MichealWen** [comment]
oh,thank you,and sorry for my poor english

**Comment by abwood** [comment]
Your English is just fine.  Thanks for your interest. I hope you enjoy the
feature when it's released.
